//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everything.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using Validations;

    [System.ComponentModel.DataAnnotations.MetadataType(typeof(OrdenValidation))]
    public partial class orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orden()
        {
            this.orden_detalle = new HashSet<orden_detalle>();
        }
    
        public int id { get; set; }
        public string orden_fecha { get; set; }
        public string delivery_fecha { get; set; }
        public string tipo_documento { get; set; }
        public int usuario { get; set; }
    
        public virtual usuario usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_detalle> orden_detalle { get; set; }
    }
}
