//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Everything.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_detalle
    {
        public int id { get; set; }
        public int orden { get; set; }
        public int producto { get; set; }
        public string cantidad { get; set; }
        public string precio { get; set; }
        public string total { get; set; }
    
        public virtual orden orden1 { get; set; }
        public virtual producto producto1 { get; set; }
    }
}
